# Generated by Django 5.0.4 on 2024-05-02 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autheur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('variete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recette.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('difficulte', models.IntegerField()),
                ('instruction', models.TextField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autheur.autheur')),
                ('ingredient', models.ManyToManyField(to='recette.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='RecetteIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unite', models.CharField(choices=[('L', 'L'), ('ml', 'ml'), ('kg', 'kg'), ('g', 'g'), ('CaC', 'CaC'), ('CaS', 'CaS')], default='g', max_length=10)),
                ('valeur', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.ingredient')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.recette')),
            ],
        ),
    ]
